# Configuration for probot/semantic-pull-requests GitHub check bot
#
# Installation/configuration docs here
# https://github.com/probot/semantic-pull-requests#configuration
#
# Always validate the PR title, and ignore the commits
titleAndCommits: true

types:
  - chore               # An internal change this is not observable by users.
  - enhancement         # Any user observable enhancement to an existing feature.
  - feat                # Any user observable new feature, such as a new platform, source, transform, or sink.
  - fix                 # Any user observable bug fix.
  - docs
  - refactor
  - build
  - perf
  - test

scopes:
  - ci
  - readme
  - script
  - e2e

  - comment
  - helper
  - mj-accordion
  - mj-accordion-element
  - mj-accordion-text
  - mj-accordion-title
  - mj-attributes
  - mj-attributes-all
  - mj-attributes-class
  - mj-attributes-element
  - mj-body
  - mj-breakpoint
  - mj-button
  - mj-carousel
  - mj-carousel-image
  - mj-column
  - mj-divider
  - mj-font
  - mj-group
  - mj-head
  - mj-hero
  - mj-image
  - mj-include
  - mj-navbar
  - mj-navbar-link
  - mj-preview
  - mj-raw
  - mj-section
  - mj-social
  - mj-social-element
  - mj-spacer
  - mj-style
  - mj-table
  - mj-text
  - mj-title
  - mj-wrapper
  - node
  - text

  - macros
  - macro common
  - macro json
  - macro mrml
  - macro parse
  - macro print

  - prelude parse
  - prelude hash
  - prelude print
  - prelude render

